### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by migueleliasweb** [princespaghetti/actionhero#3]
Hi,

It just crossed my mind it would be amazing if there was an endpoint exposed by the binary that Prometheus could query with metrics. Probably just a counter with each call name as a label.

(I'm thinking on running this as a sidecar for Kubernetes workloads)

I would be happy to help implement this feature.

Thoughts?

**Comment by princespaghetti** [comment]
Hey there,
Thanks for the interest in the tool and the feature suggestion. I can see why that'd be valuable for you use case, but it's definitely a bit beyond the scope of what I was intending. Of course you're more than welcome to fork and extend but I don't want to add the additional complexity at this time. Some of the improvements to Access Analyzer might also be a good solve for the runtime visibility: https://aws.amazon.com/blogs/security/iam-access-analyzer-makes-it-easier-to-implement-least-privilege-permissions-by-generating-iam-policies-based-on-access-activity/

**Comment by migueleliasweb** [comment]
Hi @princespaghetti ,

It's all good. I might fork and extend this them.

Awesome idea integrating with the Access Analyzer! Thanks!
